const config = [
  {
    title: {
      id: 999,
      fallback: 'What is R3BALANC3 DEX?',
    },
    description: [
      {
        id: 999,
        fallback: 'R3BALANC3 DEX is a decentralized exchange (DEX) built on the CELO blockchain. It allows users to trade digital assets in a secure, transparent, and trustless manner.',
      },
    ],
  },
  {
    title: {
      id: 999,
      fallback: 'How do I start using R3BALANC3 DEX?',
    },
    description: [
      {
        id: 999,
        fallback: 'To start using R3BALANC3 DEX, you need to have a wallet that supports CELO. Connect your wallet to the DEX and start trading by accessing the R3BALANC3 website or through compatible wallet applications.',
      },
    ],
  },
  {
    title: { id: 999, fallback: 'What tokens can I trade on R3BALANC3 DEX?' },
    description: [
      {
        id: 999,
        fallback: 'R3BALANC3 DEX supports a variety of tokens, including CELO-compatible assets. The available tokens will depend on the liquidity provided by users and the listing decisions of the R3BALANC3 team.',
      },
    ],
  },
  {
    title: { id: 999, fallback: 'How secure is R3BALANC3 DEX?' },
    description: [
      {
        id: 999,
        fallback: 'R3BALANC3 DEX leverages the security and immutability of the CELO blockchain, providing a high level of security for your trades. However, it is important to exercise caution and follow best practices for securing your wallet and private keys.',
      },
    ],
  },
  {
    title: { id: 999, fallback: 'Are there any fees associated with using R3BALANC3 DEX?' },
    description: [
      {
        id: 999,
        fallback: 'Yes, R3BALANC3 DEX charges fees on transactions to incentivize liquidity providers and cover the costs of maintaining the platform. The fee structure and rates will be transparently displayed on the DEX interface.',
      },
    ],
  },
  {
    title: { id: 999, fallback: 'How can I provide liquidity to R3BALANC3 DEX?' },
    description: [
      {
        id: 999,
        fallback: 'You can become a liquidity provider on R3BALANC3 DEX by adding your tokens to the liquidity pools. By doing so, you can earn a portion of the trading fees generated by the DEX.',
      },
    ],
  },
  {
    title: { id: 999, fallback: 'How can I contact the R3BALANC3 support team?' },
    description: [
      {
        id: 999,
        fallback: 'For any inquiries or support requests, you can reach out to the R3BALANC3 team through their official channels, such as their website, Telegram group, or social media accounts. They will be happy to assist you.',
      },
    ],
  },
];

export default config;
